name: Bug
title: "Bug Report"

body:

- type: markdown
  attributes:
    label: >
      Thank you for reporting a bug! To help us investigate the issue efficiently, please provide as much detail as possible in the following sections.

- type: input
  attributes:
    label: title
    description: Bug Title
    validations:
      required: true
    placeholder: Short and descriptive summary of the bug

- type: textarea
  attributes:
    label: description
    description: Bug Description
    validations:
      required: true
    placeholder: Describe the bug in detail, including what you expected to happen and what actually happened.

- type: textarea
  attributes:
    label: steps
    description: Steps to Reproduce
    validations:
      required: true
    placeholder: List the steps someone can take to consistently reproduce the bug.

- type: dropdown
  attributes:
    label: environment
    description: Environment
    options:
      - name: Production
      - name: Staging
      - name: Development
    validations:
      required: true

