name: Bug
title: "Bug Report"

body:

- type: markdown
  attributes:
    content: >
      Thank you for reporting a bug! To help us investigate the issue efficiently, please provide as much detail as possible in the following sections.

- type: input
  attributes:
    name: title
    label: Bug Title
    required: true
    placeholder: Short and descriptive summary of the bug

- type: textarea
  attributes:
    name: description
    label: Bug Description
    required: true
    placeholder: Describe the bug in detail, including what you expected to happen and what actually happened.

- type: textarea
  attributes:
    name: steps
    label: Steps to Reproduce
    required: true
    placeholder: List the steps someone can take to consistently reproduce the bug.

- type: dropdown
  attributes:
    name: environment
    label: Environment
    options:
      - name: Production
      - name: Staging
      - name: Development
    required: true

