name: Bug Report
description: Create an Issue
title: "Module Name: <Bug title>"
labels: ["bug", "triage"]

body:

- type: dropdown
  attributes:
    label: "SERVER <hr>"
    description: On which server the bug was found?
    multiple: true
    options:
      - Staging
      - Production
      - Development
    default: 0
  validations:
    required: true


- type: dropdown
  attributes:
    label: "BROWSER <hr>"
    description: What browsers are you seeing the problem on?
    multiple: true
    options:
      - MS Edge
      - Chrome
      - Safari
      - Arc
      - Brave
    default: 0
  validations:
    required: true


- type: input
  attributes:
    label: "File URL <hr>"
    description: Provide the file url
  validations:
    required: false

    
- type: textarea
  attributes:
    label: "Description <hr>"
    description: Bug Description
    placeholder: Describe the bug in detail. Provide Recording or Screenshots
  validations:
    required: false

- type: textarea
  attributes:
    label: "Reproduction Steps <hr>"
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
    render: bash
  validations:
    required: false


- type: textarea
  attributes:
    label: "Actual Result <hr>"
    description: What is actually happening
    placeholder: Describe the bug in detail, what actually happened.
    render: bash
  validations:
    required: false


- type: textarea
  attributes:
    label: "Expected Result <hr>"
    description: Mention your expected feature
    placeholder: Describe the bug in detail, what you expected to happen.
    render: bash
    
  validations:
    required: false

    

