name: Bug
description: Create an Issue
title: "Bug Report"
labels: [Bug, Enhancement]

body:

- type: input
  attributes:
    label: title
    description: Bug Title
    placeholder: Short and descriptive summary of the bug
  validations:
    required: true
    

- type: textarea
  attributes:
    label: description
    description: Bug Description
    placeholder: Describe the bug in detail, including what you expected to happen and what actually happened.
  validations:
    required: true

- type: textarea
  attributes:
    label: steps
    description: Steps to Reproduce
    placeholder: List the steps someone can take to consistently reproduce the bug.
  validations:
    required: true
    

- type: dropdown
  attributes:
    label: environment
    description: Environment
    options:
      - name: Production
      - name: Staging
      - name: Development
  validations:
    required: true

