name: Auto Assign Issues to Project
on:
  issues:
    types: [opened]

jobs:
  assign_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to GitHub Project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PROJECT_ID: "PVT_kwHOA8GFZM4AHqbi"  # Replace with your project ID
        run: |
          curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"content_id": "${{ github.event.issue.node_id }}", "content_type": "Issue"}' \
          https://api.github.com/projects/PVT_kwHOA8GFZM4AHqbi/columns/f75ad846/cards
